available_datasets <- function() {
  return(c("HCP1065"))
}

available_bundles <- function(dataset) {
  if (!(dataset %in% available_datasets())) {
    cli::cli_abort("Dataset not supported. Currently available datasets are {available_datasets()}.")
  }

  switch(dataset,
    "HCP1065" = names(HCP1065_ACRONYM_LIST)
  )
}

HCP1065_ACRONYM_LIST <- c(
  "Anterior Commissure" = "AC",
  "Left Arcuate Fasciculus" = "AF_L",
  "Right Arcuate Fasciculus" = "AF_R",
  "Left Acoustic Radiation" = "AR_L",
  "Right Acoustic Radiation" = "AR_R",
  "Left Frontal Parietal Cingulum" = "C_FP_L",
  "Right Frontal Parietal Cingulum" = "C_FP_R",
  "Left Frontal Parahippocampal Cingulum" = "C_FPH_L",
  "Right Frontal Parahippocampal Cingulum" = "C_FPH_R",
  "Left Parahippocampal Cingulum" = "C_PH_L",
  "Right Parahippocampal Cingulum" = "C_PH_R",
  "Left Parahippocampal Parietal Cingulum" = "C_PHP_L",
  "Right Parahippocampal Parietal Cingulum" = "C_PHP_R",
  "Left Parolfactory Cingulum" = "C_PO_L",
  "Right Parolfactory Cingulum" = "C_PO_R",
  "Left Cerebellum" = "CB_L",
  "Right Cerebellum" = "CB_R",
  "Left Corticobulbar Tract" = "CBT_L",
  "Right Corticobulbar Tract" = "CBT_R",
  "Corpus Callosum" = "CC",
  "Left Cranial Nerve II" = "CNII_L",
  "Right Cranial Nerve II" = "CNII_R",
  "Left Cranial Nerve III" = "CNIII_L",
  "Right Cranial Nerve III" = "CNIII_R",
  "Left Cranial Nerve V" = "CNV_L",
  "Right Cranial Nerve V" = "CNV_R",
  "Left Cranial Nerve VII" = "CNVII_L",
  "Right Cranial Nerve VII" = "CNVII_R",
  "Left Cranial Nerve VIII" = "CNVIII_L",
  "Right Cranial Nerve VIII" = "CNVIII_R",
  "Left Frontal Corticopontine Tract" = "CPT_F_L",
  "Right Frontal Corticopontine Tract" = "CPT_F_R",
  "Left Occipital Corticopontine Tract" = "CPT_O_L",
  "Right Occipital Corticopontine Tract" = "CPT_O_R",
  "Left Parietal Corticopontine Tract" = "CPT_P_L",
  "Right Parietal Corticopontine Tract" = "CPT_P_R",
  "Left Anterior Corticostriatal Tract" = "CS_A_L",
  "Right Anterior Corticostriatal Tract" = "CS_A_R",
  "Left Posterior Corticostriatal Tract" = "CS_P_L",
  "Right Posterior Corticostriatal Tract" = "CS_P_R",
  "Left Superior Corticostriatal Tract" = "CS_S_L",
  "Right Superior Corticostriatal Tract" = "CS_S_R",
  "Left Corticospinal Tract" = "CST_L",
  "Right Corticospinal Tract" = "CST_R",
  "Left Dentatorubrothalamic Tract" = "DRTT_L",
  "Right Dentatorubrothalamic Tract" = "DRTT_R",
  "Left Extreme Capsule" = "EMC_L",
  "Right Extreme Capsule" = "EMC_R",
  "Left Fornix" = "F_L",
  "Right Fornix" = "F_R",
  "Left Frontal Aslant Tract" = "FAT_L",
  "Right Frontal Aslant Tract" = "FAT_R",
  "Left Inferior Cerebellar Peduncle" = "ICP_L",
  "Right Inferior Cerebellar Peduncle" = "ICP_R",
  "Left Inferior Fronto-Occipital Fasciculus" = "IFOF_L",
  "Right Inferior Fronto-Occipital Fasciculus" = "IFOF_R",
  "Left Inferior Longitudinal Fasciculus" = "ILF_L",
  "Right Inferior Longitudinal Fasciculus" = "ILF_R",
  "Middle Cerebellar Peduncle" = "MCP",
  "Left Middle Longitudinal Fasciculus" = "MdLF_L",
  "Right Middle Longitudinal Fasciculus" = "MdLF_R",
  "Left Medial Lemniscus" = "ML_L",
  "Right Medial Lemniscus" = "ML_R",
  "Left Optic Radiation" = "OR_L",
  "Right Optic Radiation" = "OR_R",
  "Left Parietal Aslant Tract" = "PAT_L",
  "Right Parietal Aslant Tract" = "PAT_R",
  "Left Reticulospinal Tract" = "RST_L",
  "Right Reticulospinal Tract" = "RST_R",
  "Superior Cerebellar Peduncle" = "SCP",
  "Left Superior Longitudinal Fasciculus I" = "SLF1_L",
  "Right Superior Longitudinal Fasciculus I" = "SLF1_R",
  "Left Superior Longitudinal Fasciculus II" = "SLF2_L",
  "Right Superior Longitudinal Fasciculus II" = "SLF2_R",
  "Left Superior Longitudinal Fasciculus III" = "SLF3_L",
  "Right Superior Longitudinal Fasciculus III" = "SLF3_R",
  "Left Anterior Thalamic Radiation" = "TR_A_L",
  "Right Anterior Thalamic Radiation" = "TR_A_R",
  "Left Posterior Thalamic Radiation" = "TR_P_L",
  "Right Posterior Thalamic Radiation" = "TR_P_R",
  "Left Superior Thalamic Radiation" = "TR_S_L",
  "Right Superior Thalamic Radiation" = "TR_S_R",
  "Left Uncinate Fasciculus" = "UF_L",
  "Right Uncinate Fasciculus" = "UF_R",
  "Vermis" = "V",
  "Left Vertical Occipital Fasciculus" = "VOF_L",
  "Right Vertical Occipital Fasciculus" = "VOF_R"
)

